# this is a docker compose file for the simulation application
# which includes a React frontend, Node.js backend, PostgreSQL database, and nginx reverse proxy
version: '3.8'
services:
  react-app:
    build: .
    container_name: react-app-container
    # ports:
    #   - "3000:3000"  # Remove external port - nginx handles all traffic
    expose:
      - "3000"  # Internal port for nginx proxy
    environment:
      - VITE_HOST=0.0.0.0  # Ensure Vite binds to all interfaces
    depends_on:
      - backend
      - db
    networks:
      - app-network
  
  backend:
    build: ./backend
    container_name: backend-container
    # ports:
    #   - "4001:5000"  # Remove external port - nginx handles all traffic
    expose:
      - "5000"  # Internal port for nginx proxy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=simdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network
  
  # nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"  # Disable HTTPS for now
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./dist:/var/www/html  # Not needed for proxy mode
      # - ./ssl:/etc/nginx/ssl  # Add SSL certificates here
    depends_on:
      - react-app
      - backend
    networks:
      - app-network
  
  db:
    build: ./database
    container_name: simdb-container
    environment:
      - POSTGRES_DB=simdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge