# this is a docker compose file for the simulation application
# which includes a React frontend, Node.js backend, and PostgreSQL database
version: '3.8'
services:
  react-app:
    build: .
    container_name: react-app-container
    ports:
      - "80:3000"
    depends_on:
      - backend
      - db
  
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "4001:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=simdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  
  db:
    build: ./database
    container_name: simdb-container
    environment:
      - POSTGRES_DB=simdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: