# This is a Github Action workflow which will 
# SHH into a remote server
# Pull the latest code from a github repo
# build a docker image
# run the docker image
# This workflow is triggered on every push to the main branch
name: Deploy Node.js App to Remote Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /crocodilo/sunhacks-crocodilo
            git pull origin main
            docker build -t nodejs-app .
            docker stop nodejs-app || true
            docker rm nodejs-app || true
            docker run -d -p 3000:3000 --name nodejs-app nodejs-app
          EOF
